from django.urls import path
from . import views
urlpatterns = [
       path('register/', views.register, name='register'),
       path('userinfo/', views.user_info, name='userinfo'),
       path('login_user/', views.login_user, name='login_user'),
       path('login/', views.login, name='login'),
       path('google-callback/', views.google_callback, name='google_callback'),
       path('set-role/', views.set_role, name='set_role'),
       path('add_role/', views.add_role, name='add_role'),
       path('check_token_acc/', views.check_token_acc, name='check_token_acc'),
#----------------- chức năng của partner--------------------------------
       path('edit_profile/', views.edit_profile, name='edit_profile'),
       path('get_list_hotel/', views.get_list_hotel, name='get_list_hotel'),
       path('add_hotel/', views.add_hotel, name='add_hotel'),
       path('edit_hotel/<int:id>/', views.edit_hotel, name='edit_hotel'),
       path('delete_hotel/<int:id>/', views.delete_hotel, name='delete_hotel'),
       path('upload/', views.upload_image, name='upload_image'),
       path('get_list_typeroom/', views.get_list_typeroom, name='get_list_typeroom'),
       path('add_typeroom/<int:id>/', views.add_typeroom, name='add_typeroom'),
       path('edit_typeroom/<int:id>/', views.edit_typeroom, name='edit_typeroom'),
       path('delete_typeroom/<int:id>/', views.delete_typeroom, name='delete_typeroom'),
       path('get_list_room/', views.get_list_room, name='get_list_room'),
       path('get_list_utitlity/', views.get_list_utitlity, name='get_list_utitlity'),
       path('add_room/<int:id>/', views.add_room, name='add_room'),
       path('edit_room/<int:id>/', views.edit_room, name='edit_room'),
       path('delete_room/<int:id>/', views.delete_room, name='delete_room'),
       path('lst_order/<int:id>/', views.lst_order, name='lst_order'),
       path('update_status_room/', views.update_status_room, name='update_status_room'),
       path('get_month_and_hotel/', views.get_month_and_hotel, name='get_month_and_hotel'),
       path('revenue_by_month/<int:hotel_id>/<int:year>/', views.revenue_by_month, name='revenue_by_month'),
#----------------- view của partner--------------------------------  
       path('partner/home/', views.partner_home, name='partnerhome'),
       path('partner/hotel/', views.partner_hotel, name='partnerhotel'),
       path('partner/create-hotel/', views.partner_add_hotel, name='partner-create-hotel'),
       path('partner/edit-hotel/<int:id>/', views.partner_edit_hotel, name='partner_edit_hotel'),
       path('partner/detail-hotel/<int:id>/', views.partner_get_typeroom, name='partner_get_typeroom'),
       path('partner/create-typeroom/<int:id>/', views.partner_add_typeroom, name='partner_add_typeroom'),
       path('partner/edit-typeroom/<int:id>/<int:hotel>/', views.partner_edit_typeroom, name='partner_edit_typeroom'),
       path('partner/detail-room/<int:id>/<int:hotel>/', views.partner_get_room, name='partner_get_room'),
       path('partner/add-room/<int:id>/<int:hotel>/', views.partner_add_room, name='partner_add_room'),
       path('partner/edit-room/<int:id>/<int:type>/<int:hotel>/', views.partner_edit_room, name='partner_edit_room'),
       path('partner/profile/', views.partner_profile, name='partner_profile'),
       path('partner/order/<int:id>/', views.partner_order, name='partner_order'),
       path('partner/statistic/', views.partner_statistic, name='partner_statistic'),
#----------------- chức năng của customer--------------------------------
       path('list_hotels/', views.list_hotel, name='list_hotel'),
       path('detail_hotel/<int:id>/<str:start_date>/<str:end_date>/', views.detail_hotel, name='detail_hotel'),
       path('count_item_cart/', views.count_item_cart, name='count_item_cart'),
       path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
       path('list_in_cart/', views.list_in_cart, name='list_in_cart'),
       path('delete_item_cart/<int:id>/', views.delete_item_cart, name='delete_item_cart'),
       path('item_order/<int:id>/', views.item_order, name='item_order'),
       path('store_cart/', views.store_cart, name='store_cart'),
       path('show_store_cart/', views.show_store_cart, name='show_store_cart'),
       path('customer_edit_profile/', views.customer_edit_profile, name='customer_edit_profile'),
       path('item_booking/', views.item_booking, name='item_booking'),
       path('order_booking/', views.order_booking, name='order_booking'),
       path('clear_cart/', views.clear_cart, name='clear_cart'),
       path('my_order/', views.my_order, name='my_order'),
       path('cancel_order_or_room/', views.cancel_order_or_room, name='cancel_order_or_room'),
       path('add_review/', views.add_review, name='add_review'),
       path('lst_review/', views.lst_review, name='lst_review'),
       path('show_review/<int:id>/', views.show_review, name='show_review'),
       path('re_book/', views.re_book_order, name='re_book_order'),
       #-----------------------Thanh toán------------------------
       path('return_page/', views.return_page, name='return_page'),
       path('success_paypal/', views.success_paypal, name='success_paypal'),
       path('success_zalopay/', views.success_zalopay, name='success_zalopay'),
       path('zalo_payment/', views.zalo_payment, name='zalo_payment'), 
       path('callback/', views.callback, name='callback'),
       path('create_momo_payment/', views.create_momo_payment, name='create_momo_payment'), 
       path('handle_payment_momo_callback/', views.handle_payment_momo_callback, name='handle_payment_momo_callback'),
       path('payment_paypal/', views.payment_paypal, name='payment_paypal'),
#----------------- view của customer--------------------------------
       path('customer/home/', views.customer_home, name='customerhome'),
       path('customer/hotel/', views.customer_hotels, name='customer_hotels'),
       path('customer/detail-hotel/<int:id>', views.customer_detail_hotel, name='customer_detail_hotel'),
       path('customer/cart/', views.customer_cart, name='customer_cart'),
       path('customer/book/<int:id>', views.customer_order, name='customer_order'),
       path('customer/book/', views.customer_cart_to_order, name='customer_cart_to_order'),
       path('customer/profile/', views.customer_profile, name='customer_profile'),
       path('return-payment/', views.customer_pay_return, name='customer_pay_return'),
       path('customer/my-order/', views.customer_my_order, name='customer_my_order'),
       path('customer/review/', views.customer_review, name='customer_review'),
#----------------- chức năng của admin--------------------------------
       path('admin_login_page/', views.admin_login_page, name='admin_login_page'),
       path('get_list_users/', views.get_list_users, name='get_list_users'),
       path('get_list_hotels/', views.get_list_hotels, name='get_list_hotels'),
       path('confirm_hotel/<int:id>/', views.confirm_hotel, name='confirm_hotel'),
       path('lock_account/<str:email>/', views.lock_account, name='lock_account'),
       path('list_order/', views.list_order, name='list_order'),
       path('update_status_order/', views.update_status_order, name='update_status_order'),
       path('revenue_report/', views.revenue_report, name='revenue_report'),
       path('hotel_traffic_report/', views.hotel_traffic_report, name='hotel_traffic_report'),
       path('get_month_and_year/', views.get_month_and_year, name='get_month_and_year'),
       path('potential_customers/', views.potential_customers, name='potential_customers'),
       path('send_email/', views.send_email_to_hotel, name='send_email_to_hotel'),
   
#----------------- view của admin--------------------------------
       path('ad/login/', views.admin_login, name='admin_login'),
       path('ad/home/', views.admin_home, name='admin_home'),
       path('ad/manage-user/', views.admin_manage_user, name='admin_manage_user'),
       path('ad/manage-hotel/', views.admin_manage_hotel, name='admin_manage_hotel'),
       path('ad/manage-order/', views.admin_manage_order, name='admin_manage_order'),
       path('ad/revenue-report/', views.admin_revenue_report, name='admin_revenue_report'),
       path('ad/traffic-report/', views.admin_traffic_report, name='admin_traffic_report'),
       path('ad/customer-report/', views.admin_customer_report, name='admin_customer_report'),
]