# Generated by Django 5.1.4 on 2025-03-11 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                ("idbook", models.AutoField(primary_key=True, serialize=False)),
                ("iscancel", models.BooleanField(default=False)),
                ("iscomplete", models.BooleanField(default=False)),
                ("total_cost", models.FloatField(null=True)),
                ("state", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "booking",
            },
        ),
        migrations.CreateModel(
            name="customer",
            fields=[
                ("idcustomer", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "customer",
            },
        ),
        migrations.CreateModel(
            name="partner",
            fields=[
                ("idpartner", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "partner",
            },
        ),
        migrations.CreateModel(
            name="role",
            fields=[
                ("idrole", models.IntegerField(primary_key=True, serialize=False)),
                ("role_name", models.TextField()),
                ("profession", models.TextField()),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="room_detail",
            fields=[
                ("idroom", models.AutoField(primary_key=True, serialize=False)),
                ("price_only_day", models.IntegerField()),
                ("quantity", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "room_detail",
            },
        ),
        migrations.CreateModel(
            name="service",
            fields=[
                ("idsv", models.IntegerField(primary_key=True, serialize=False)),
                ("service", models.TextField()),
            ],
            options={
                "db_table": "service",
            },
        ),
        migrations.CreateModel(
            name="type_customer",
            fields=[
                ("idtypecusm", models.IntegerField(primary_key=True, serialize=False)),
                ("type_customer", models.TextField()),
            ],
            options={
                "db_table": "type_customer",
            },
        ),
        migrations.CreateModel(
            name="type_payment",
            fields=[
                ("idpayment", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_name", models.TextField()),
            ],
            options={
                "db_table": "type_payment",
            },
        ),
        migrations.CreateModel(
            name="booking_detail",
            fields=[
                ("iddetail", models.AutoField(primary_key=True, serialize=False)),
                ("date_arrive", models.DateField()),
                ("date_leave", models.DateField()),
                ("iscancel", models.BooleanField(default=False)),
                ("is_review", models.BooleanField(default=False)),
                ("status", models.TextField()),
                ("date_payment", models.DateTimeField(null=True)),
                (
                    "idbook",
                    models.ForeignKey(
                        db_column="idbook",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.booking",
                    ),
                ),
                (
                    "idroom",
                    models.ForeignKey(
                        db_column="idroom",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.room_detail",
                    ),
                ),
            ],
            options={
                "db_table": "booking_detail",
                "unique_together": {("idbook", "idroom")},
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="idcustomer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.customer",
            ),
        ),
        migrations.CreateModel(
            name="hotels",
            fields=[
                ("idhotel", models.AutoField(primary_key=True, serialize=False)),
                ("htl_name", models.TextField()),
                ("htl_img", models.TextField()),
                ("address", models.TextField()),
                ("description", models.TextField()),
                ("begin_price", models.IntegerField()),
                ("is_confirm", models.BooleanField(default=False)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "idpartner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.partner",
                    ),
                ),
            ],
            options={
                "db_table": "hotels",
            },
        ),
        migrations.CreateModel(
            name="rating",
            fields=[
                ("idrate", models.AutoField(primary_key=True, serialize=False)),
                ("score_clean", models.FloatField()),
                ("score_utility", models.FloatField()),
                ("score_service", models.FloatField()),
                ("score_location", models.FloatField()),
                ("score_cost", models.FloatField()),
                ("rate", models.FloatField()),
                ("title", models.TextField()),
                ("commend", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "iddetail",
                    models.ForeignKey(
                        db_column="iddetail",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.booking_detail",
                    ),
                ),
            ],
            options={
                "db_table": "rating",
            },
        ),
        migrations.CreateModel(
            name="account",
            fields=[
                (
                    "email",
                    models.CharField(max_length=320, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=128)),
                ("token", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "idrole",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.role",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                ("idcart", models.AutoField(primary_key=True, serialize=False)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "idcustomer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.customer",
                    ),
                ),
                (
                    "idroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.room_detail",
                    ),
                ),
            ],
            options={
                "db_table": "cart",
            },
        ),
        migrations.CreateModel(
            name="capacity",
            fields=[
                ("idcap", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "idroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.room_detail",
                    ),
                ),
                (
                    "idtypecusm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.type_customer",
                    ),
                ),
            ],
            options={
                "db_table": "capacity",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="idpayment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.type_payment",
            ),
        ),
        migrations.CreateModel(
            name="type_room",
            fields=[
                ("idtyperm", models.AutoField(primary_key=True, serialize=False)),
                ("type_room", models.TextField(null=True)),
                ("bed", models.TextField(null=True)),
                ("area", models.FloatField(null=True)),
                ("room_img", models.TextField()),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "idhotel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.hotels",
                    ),
                ),
            ],
            options={
                "db_table": "type_room",
            },
        ),
        migrations.AddField(
            model_name="room_detail",
            name="idtyperm",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.type_room",
            ),
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("phonenumber", models.CharField()),
                (
                    "email",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.account",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.AddField(
            model_name="partner",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.users",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="myapp.users",
            ),
        ),
        migrations.CreateModel(
            name="utility",
            fields=[
                ("idulty", models.AutoField(primary_key=True, serialize=False)),
                (
                    "idroom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.room_detail",
                    ),
                ),
                (
                    "idsv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="myapp.service",
                    ),
                ),
            ],
            options={
                "db_table": "utility",
            },
        ),
    ]
